[project]
org-name = "ballerina"
version = "0.0.0"

[platform]
target = "java11"

    [[platform.libraries]]
        artifactId = "mock"
        version = "0.0.0"
        path = "./lib/testerina-core-2.0.0-Preview6-SNAPSHOT.jar"
        groupId = "ballerina"
