name: Build merged PR changes on Ubuntu

on:
  push:
    branches:
      - master
      - next-release
      - release-stage
      - stage
      - ballerina-[0-9]+.[0-9]+.x

jobs:
  ubuntu_push_build:
    name: Build merged PR changes
    runs-on: ubuntu-latest
    timeout-minutes: 75

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build without integration test
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          ./gradlew build -x createJavadoc -x :jballerina-integration-test:test -x :ballerina-mysql:test -x :ballerina-http:test -x :ballerina-kafka:test --max-workers=2 --scan

          find ~/.gradle/caches/ -name "*.lock" -type f -delete

      - name: Run few other tests
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          ./gradlew :ballerina-mysql:test :ballerina-http:test :ballerina-kafka:test -x createJavadoc --no-parallel --scan

          find ~/.gradle/caches/ -name "*.lock" -type f -delete

      - name: Run integration test
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          ./gradlew :jballerina-integration-test:test -x createJavadoc --no-parallel --scan

          find ~/.gradle/caches/ -name "*.lock" -type f -delete

